#############################################################################
# Makefile for building: YSU_2021_Infantry
# Generated by qmake (3.1) (Qt 5.14.1)
# Project:  YSU_2021_Infantry.pro
# Template: app
# Command: /home/mazixi/Qt5.14.1/5.14.1/gcc_64/bin/qmake -o Makefile YSU_2021_Infantry.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++1y -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/local/include -isystem /usr/local/include/opencv -isystem /usr/local/include/opencv2 -I../../Environment/linuxSDK_V2.1.0.2/include -I../../Qt5.14.1/5.14.1/gcc_64/mkspecs/linux-g++
QMAKE         = /home/mazixi/Qt5.14.1/5.14.1/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/mazixi/Qt5.14.1/5.14.1/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/mazixi/Qt5.14.1/5.14.1/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = YSU_2021_Infantry1.0.0
DISTDIR = /home/mazixi/桌面/YSU_2021_Infantrybb/.tmp/YSU_2021_Infantry1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) /usr/local/lib/libopencv_calib3d.so /usr/local/lib/libopencv_core.so /usr/local/lib/libopencv_features2d.so /usr/local/lib/libopencv_flann.so /usr/local/lib/libopencv_highgui.so /usr/local/lib/libopencv_imgcodecs.so /usr/local/lib/libopencv_imgproc.so /usr/local/lib/libopencv_ml.so /usr/local/lib/libopencv_objdetect.so /usr/local/lib/libopencv_photo.so /usr/local/lib/libopencv_shape.so /usr/local/lib/libopencv_stitching.so /usr/local/lib/libopencv_superres.so /usr/local/lib/libopencv_videoio.so /usr/local/lib/libopencv_video.so /usr/local/lib/libopencv_videostab.so /home/mazixi/Environment/linuxSDK_V2.1.0.2/lib/x64/libMVSDK.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ThreadManager/thread_manager.cpp \
		ArmorDetector/armor_detector.cpp \
		RuneDetector/rune_detector.cpp \
		CameraManager/camera_manager.cpp \
		Classify/classify.cpp \
		Communication/communication.cpp \
		Main/main.cpp \
		Pose/angle_solver.cpp 
OBJECTS       = thread_manager.o \
		armor_detector.o \
		rune_detector.o \
		camera_manager.o \
		classify.o \
		communication.o \
		main.o \
		angle_solver.o
DIST          = ../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/toolchain.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/qmake_use.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/lex.prf \
		YSU_2021_Infantry.pro ThreadManager/thread_manager.h \
		ArmorDetector/armor_detector.h \
		RuneDetector/rune_detector.h \
		CameraManager/camera_manager.h \
		Classify/classify.h \
		Communication/communication.h \
		Pose/angle_solver.h \
		Main/headfiles.h ThreadManager/thread_manager.cpp \
		ArmorDetector/armor_detector.cpp \
		RuneDetector/rune_detector.cpp \
		CameraManager/camera_manager.cpp \
		Classify/classify.cpp \
		Communication/communication.cpp \
		Main/main.cpp \
		Pose/angle_solver.cpp
QMAKE_TARGET  = YSU_2021_Infantry
DESTDIR       = 
TARGET        = YSU_2021_Infantry


first: all
####### Build rules

YSU_2021_Infantry:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: YSU_2021_Infantry.pro ../../Qt5.14.1/5.14.1/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/toolchain.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/qmake_use.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/lex.prf \
		YSU_2021_Infantry.pro
	$(QMAKE) -o Makefile YSU_2021_Infantry.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/unix.conf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/linux.conf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/sanitize.conf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/g++-base.conf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/qconfig.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/qt_config.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/toolchain.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/default_pre.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/default_post.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/qml_debug.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/warn_on.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/qt.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/unix/thread.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/qmake_use.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/file_copies.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/exceptions.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/yacc.prf:
../../Qt5.14.1/5.14.1/gcc_64/mkspecs/features/lex.prf:
YSU_2021_Infantry.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile YSU_2021_Infantry.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile YSU_2021_Infantry

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

thread_manager.o: ThreadManager/thread_manager.cpp Main/headfiles.h \
		ThreadManager/thread_manager.h \
		ArmorDetector/armor_detector.h \
		CameraManager/camera_manager.h \
		../../Environment/linuxSDK_V2.1.0.2/include/CameraApi.h \
		../../Environment/linuxSDK_V2.1.0.2/include/CameraDefine.h \
		../../Environment/linuxSDK_V2.1.0.2/include/CameraStatus.h \
		Pose/angle_solver.h \
		Communication/communication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thread_manager.o ThreadManager/thread_manager.cpp

armor_detector.o: ArmorDetector/armor_detector.cpp Main/headfiles.h \
		ArmorDetector/armor_detector.h \
		Pose/angle_solver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armor_detector.o ArmorDetector/armor_detector.cpp

rune_detector.o: RuneDetector/rune_detector.cpp Main/headfiles.h \
		RuneDetector/rune_detector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rune_detector.o RuneDetector/rune_detector.cpp

camera_manager.o: CameraManager/camera_manager.cpp Main/headfiles.h \
		CameraManager/camera_manager.h \
		../../Environment/linuxSDK_V2.1.0.2/include/CameraApi.h \
		../../Environment/linuxSDK_V2.1.0.2/include/CameraDefine.h \
		../../Environment/linuxSDK_V2.1.0.2/include/CameraStatus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera_manager.o CameraManager/camera_manager.cpp

classify.o: Classify/classify.cpp Main/headfiles.h \
		Classify/classify.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classify.o Classify/classify.cpp

communication.o: Communication/communication.cpp Main/headfiles.h \
		Communication/communication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o communication.o Communication/communication.cpp

main.o: Main/main.cpp Main/headfiles.h \
		ThreadManager/thread_manager.h \
		ArmorDetector/armor_detector.h \
		CameraManager/camera_manager.h \
		../../Environment/linuxSDK_V2.1.0.2/include/CameraApi.h \
		../../Environment/linuxSDK_V2.1.0.2/include/CameraDefine.h \
		../../Environment/linuxSDK_V2.1.0.2/include/CameraStatus.h \
		Pose/angle_solver.h \
		Communication/communication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o Main/main.cpp

angle_solver.o: Pose/angle_solver.cpp Main/headfiles.h \
		Pose/angle_solver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o angle_solver.o Pose/angle_solver.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

